### ISSUE TITLE
[Suggestion] Make key configurable

### ISSUE THREAD

**Issue by carstorm** [MattCzyr/Calculations#2]
Allow the key to open the GUI be set in the controls.

**Comment by MattCzyr** [comment]
The keybind can already be changed in controls. It will probably be at the bottom of the vanilla list, but probably above most other modded keybinds.

![calculations](https://user-images.githubusercontent.com/14143296/28670301-0c1661b6-72a6-11e7-9930-f06cefe1eb95.png)

**Comment by carstorm** [comment]
Ahh sorry, based on the description on the Curse page, I though it was hard-coded. (Haven't had a chance yet to play with the mod)

**Comment by MattCzyr** [comment]
I'll take another look at the Curse project page and edit the description if necessary. Thanks for the heads up about it.
